### ISSUE TITLE
В чем преимущество использования двух идентичных массивов this.actorArrayOfObj и this.actors?

### ISSUE THREAD

**Issue by frontgirl** [AlexanderBardin/js_exam_work#3]
https://github.com/AlexanderBardin/js_exam_work/blob/8a26e81fabd5b76e4bd99b477bdb82b88ad6acd3/game.js#L100

**Comment by AlexanderBardin** [comment]
по заданию нужно свойство actors   а  this.actorArrayOfObj  сделал по инерции т.к. свойство есть и не изменил потом
